


ui_vis1 <- fluidPage(
    tabsetPanel(
      tabPanel("Day",
             # Application title
             titlePanel("Daily sea surface temperatures in the North Pacific"),
             p("Select a state statistical area and NMFS reporting area to view a sample of the daily data. To filter by only one of these fields, select 'All' in the other. To view all data, select 'All' in both dropdown boxes. Download buttons will deliver filtered versions of the data if you have selected particular areas. To download the full dataset, select 'All' in both dropdown menus. If working in R, the 'Download RDS' option is recommended and will yield a smaller file size (~50mb) than csv (~500mb). The full dataset is nearly 10 million rows. You can also filter each field using the dialogue boxes beneath each column."),
             br(),
             p("See the 'More Information' tab (or the metadata) for descriptions of each variable."),
             fluidRow(
               column(3,
                      selectInput("stat6list","Select state statistical area",choices=mystats,multiple=TRUE)),
               column(3,
                      selectInput("nmfsarealist","Select NMFS reporting area",choices=mynmfsall,multiple=TRUE)),
               column(3,downloadButton("downloadData_csv", "Download csv"),
                      downloadButton("downloadData_RDS", "Download RDS"))),
               fluidRow(shiny::dataTableOutput("table1"))
    ),
    tabPanel("Weekly",
             # Application title
             titlePanel("Weekly sea surface temperatures in the North Pacific"),
             p("Select a state statistical area and NMFS reporting area to view a sample of the weekly data. To filter by only one of these fields, select 'All' in the other. To view all data, select 'All' in both dropdown boxes. Download buttons will deliver filtered versions of the data if you have selected particular areas. To download the full dataset, select 'All' in both dropdown menus. If working in R, the 'Download RDS' option is recommended and will yield a smaller file size than csv. The full dataset is nearly 1.5 million rows. You can also filter each field using the dialogue boxes beneath each column."),
             br(),
             p("See the 'More Information' tab (or the metadata) for descriptions of each variable."),
             br(),
             fluidRow(
               column(3,
                      selectInput("stat6list2","Select state statistical area",choices=mystats,multiple=TRUE)),
               column(3,
                      selectInput("nmfsarealist2","Select NMFS reporting area",choices=mynmfsall,multiple=TRUE)),
               column(3,downloadButton("downloadWeekly_csv", "Download csv"),
                      downloadButton("downloadWeekly_RDS", "Download RDS"))),
               fluidRow(shiny::dataTableOutput("table2"))
             ),
    tabPanel("Monthly",
             # Application title
             titlePanel("Monthly sea surface temperatures in the North Pacific"),
             p("Select a state statistical area and NMFS reporting area to view a sample of the monthly data. To filter by only one of these fields, select 'All' in the other. To view all data, select 'All' in both dropdown boxes. Download buttons will deliver filtered versions of the data if you have selected particular areas. To download the full dataset, select 'All' in both dropdown menus. If working in R, the 'Download RDS' option is recommended and will yield a smaller file size than csv. The full dataset is nearly 320,000 rows. You can also filter each field using the dialogue boxes beneath each column."),
             br(),
             p("See the 'More Information' tab (or the metadata) for descriptions of each variable."),
             br(),
             fluidRow(
               column(3,
                      selectInput("stat6list3","Select state statistical area",choices=mystats,multiple=TRUE)),
               column(3,
                      selectInput("nmfsarealist3","Select NMFS reporting area",choices=mynmfsall,multiple=TRUE)),
               column(3,downloadButton("downloadMonthly_csv", "Download csv"),
                      downloadButton("downloadMonthly_RDS", "Download RDS"))),
             fluidRow(shiny::dataTableOutput("table3"))
    ),
    tabPanel("More Information",   # Information about data collection.
             "See metadate file for complete description of the data and extraction process",
             br(),
             br(),
             strong("Variable descriptions:"), 
             br(),
             br(),
             strong("sst.mean")," = Average sea surface temperature across the queried spatial stratum (e.g., STAT_AREA or NMFSAREA) during the queried time period (e.g., day, week, month).",
             br(),
             br(),
             strong("date")," = calendar date between 01 Jan 2003 and 10 May 2018",
             br(),
             br(),
             strong("STAT_AREA")," = Alaska Dept of Fish and Game stat6 groundfish management area",
             br(),
             br(),
             strong("FMP_AREA_C")," = Fishery management plan area (e.g., Bering Sea Aleutian Islands, Gulf of Alaska)",
             br(),
             br(),
             strong("IFQ_SABLEF")," = Sablefish management areas",
             br(),
             br(),
             strong("STATEFED")," = Flag identifying whether a stat area occurs in state or federal waters",
             br(),
             br(),
             strong("GOA")," = Delimiter for NMFS GOA management areas (eastern, central or western GOA)",
             br(),
             br(),
             strong("sst.sd")," = For daily STAT_AREA query, standard deviation of daily sst values per STAT_AREA. For coarser spatial or temporal queries, this is the standard deviation of sst values from the daily STAT_AREA, but does not propagate the original standard deviations.",
             br(),
             br(),
             strong("year")," = year corresponding to the days, weeks, or months that were aggregated.",
             br(),
             br(),
             strong("month")," = month corresponding to the days or weeks that were aggregated.",
             br(),
             br(),
             strong("week")," =  week, beginning on Sunday, corresponding to the days that were aggregated.",
             br(),
             br(),
             strong("julian")," = julian day for a given date",
             br(),
             br(),
             strong("min and max lons and lats")," = bounding box coordinates for a given STAT_AREA",
             br(),
             br(),
             strong("m.depth")," = mean depth for a given STAT_AREA in meters. This field is dropped for coarser spatial areas.",
             br(),
             br(),
             strong("sd.depth")," = standard deviation of depth for a given STAT_AREA. Useful for identifiying regions occurring on the continental slope")
    ))

