


ui_vis1 <- fluidPage(
  tabsetPanel(
    tabPanel("Sea surface temperatures by ADF&G statistical areas",
             # Application title
             br(),
             p("Select an ADF&G statistical area to view daily data or data averaged by week or month."),
             br(),
             p("Download buttons will deliver the version of the data selected. 'Download RDS' (recommended for R users) will yield smaller files than 'Download csv`."),
             br(),
             p("See the 'More Information' tab (or the metadata) for descriptions of each variable."),
             br(),
             p("WARNING!! The full dataset is nearly 10 million rows so selections with many areas may take a few minutes to load."),
             fluidRow(
               column(4,
                      selectInput("mystattable", "Display data as daily, weekly, or monthly:", 
                                  choices = c("Daily", "Weekly average","Monthly average"))),
               column(4,
                      pickerInput("statarealist","Select ADF&G statistical area", choices=mystats, options = list(`actions-box` = TRUE),multiple = T)),
               column(4,downloadButton("download_stat_area_csv", "Download csv"),
                      downloadButton("download_stat_area_RDS", "Download RDS"))),
             fluidRow(
               column(12,shiny::dataTableOutput("table1") %>% withSpinner(color="#0dc5c1")))
    ),
  tabPanel("Sea surface temperatures by NMFS reporting areas",
           # Application title
           br(),
           p("Select a NMFS reporting area to view daily data or data averaged by week or month."),
           br(),
           p("Download buttons will deliver the version of the data selected. 'Download RDS' (recommended for R users) will yield smaller files than 'Download csv`."),
           br(),
           p("See the 'More Information' tab (or the metadata) for descriptions of each variable."),
           br(),
           p("WARNING!! The full dataset is nearly 10 million rows so selections with many areas may take a few minutes to load."),
           fluidRow(
             column(4,
                    selectInput("mynmfstable", "Display data as daily, weekly, or monthly:", 
                                choices = c("Daily", "Weekly average","Monthly average"))),
             column(4,
                    pickerInput("nmfsarealist","Select NMFS reporting area", choices=mynmfsall, options = list(`actions-box` = TRUE),multiple = T)),
             column(4,downloadButton("download_nmfs_area_csv", "Download csv"),
                    downloadButton("download_nmfs_area_RDS", "Download RDS"))),
           fluidRow(
             column(12,shiny::dataTableOutput("table2") %>% withSpinner(color="#0dc5c1")))
  ),
  tabPanel("More Information",   # Information about data collection.
           "See metadate file for complete description of the data and extraction process",
           br(),
           br(),
           strong("Variable descriptions:"), 
           br(),
           br(),
           strong("sst.mean")," = Average sea surface temperature across the queried spatial stratum (e.g., STAT_AREA or NMFSAREA) during the queried time period (e.g., day, week, month).",
           br(),
           br(),
           strong("date")," = calendar date between 01 Jan 2003 and 10 May 2018",
           br(),
           br(),
           strong("STAT_AREA")," = Alaska Dept of Fish and Game stat6 groundfish management area. For maps of the NMFS reporting areas visit www.adfg.alaska.gov/index.cfm?adfg=fishingCommercialByFishery.statmaps.",
           br(),
           br(),
           strong("NMFSAREA")," = NMFS reporting areas as described in the manuscript text. For maps of the NMFS reporting areas visit https://alaskafisheries.noaa.gov/maps.",
           br(),
           br(),
           strong("FMP_AREA_C")," = Fishery management plan area (e.g., Bering Sea Aleutian Islands, Gulf of Alaska)",
           br(),
           br(),
           strong("STATEFED")," = Flag identifying whether a stat area occurs in state or federal waters",
           br(),
           br(),
           strong("sst.sd")," = For daily STAT_AREA query, standard deviation of daily sst values per STAT_AREA. For coarser spatial or temporal queries, this is the standard deviation of sst values from the daily STAT_AREA, but does not propagate the original standard deviations.",
           br(),
           br(),
           strong("year")," = year corresponding to the days, weeks, or months that were aggregated.",
           br(),
           br(),
           strong("month")," = month corresponding to the days or weeks that were aggregated.",
           br(),
           br(),
           strong("week")," =  week, beginning on Sunday, corresponding to the days that were aggregated.",
           br(),
           br(),
           strong("julian")," = julian day for a given date",
           br(),
           br(),
           strong("min and max lons and lats")," = bounding box coordinates for a given STAT_AREA",
           br(),
           br(),
           strong("m.depth")," = mean depth for a given STAT_AREA in meters. This field is dropped for coarser spatial areas.",
           br(),
           br(),
           strong("sd.depth")," = standard deviation of depth for a given STAT_AREA. Useful for identifiying regions occurring on the continental slope")
  
))